############################################################
include $(addprefix $(ORIGINAL), make.ini)
############################################################
#		variable
############################################################

INCLUDE = ./ ../LionX/ ../Protocol/
LIBS = LionX
LIBDIRS = ../LionX/
TARGETS = 
ARCHIVER =
SRC = Supervisor.cc
OUTDIR = ../Output/
CLEAN =

############################################################
include $(addprefix $(ORIGINAL), make.rule)
############################################################
